[package]
name = "toqc/framework"
version = "0.1.4"
description = "A Simple Framework for Roblox Games."
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["lib","default.project.json","LICENSE"]
exclude = ["selene.toml","README.md","rokit.toml"]